apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-frontend
  labels:
    team: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-pod
  template:
    metadata:
      labels:
        app: frontend-pod
    spec:
      containers:
        - name: frontend-container
          image: ozgurozturknet/k8s:latest
          ports:
            - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-backend
  labels:
    team: development
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-pods
  template:
    metadata:
      labels:
        app: backend-pods
    spec:
      containers:
      - name: backend-containers
        image: ozgurozturknet/k8s:backend
        ports:
        - containerPort: 5000