apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  labels:
    environment: dev
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: m_nginx
  template:
    metadata:
      labels:
        app: m_nginx
    spec:
      containers:
      - name: mynginx
        image: nginx
        ports:
        - containerPort: 80