apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vol-db
spec:
  storageClassName: db-vol-class
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ubuntu/pv-data"
