apiVersion: v1
kind: Service
metadata:
  name: db-deployment-service
  labels:
    svccIPbind: mongo-deploy-svc
    svcname: mongo-svc
spec:
  selector:
    svcname: mongo-svc
  type: ClusterIP
  ports:
    - name: db-mongo-port
      port: 21017
      targetPort: 21017
