apiVersion: v1
kind: Service   
metadata:
  name: web-flask-svc-nodeport
  labels:
    app: web-flask-nodeport
spec:
  selector:
    svc: front-end
  type: NodePort  
  ports:
  - port: 3000  
    targetPort: 5000
